version: '3.8'

services:
  node:
    build: .
    depends_on:
      - geth
    ports:
      - 7545:8545     # RPC
      - 9222:9222     # P2P TCP
      - 9222:9222/udp # P2P UDP
      - 7300:7300     # metrics
      - 6060:6060     # pprof
    command: [ "bash", "./op-node-entrypoint" ]
    env_file:
      - .env.default
      - networks/zora-mainnet-0/.env
      - .env
    volumes:
      - ./networks/zora-mainnet-0/rollup.json:/rollup.json
      - ./networks/zora-mainnet-0/genesis.json:/genesis.json
